FROM node AS build

WORKDIR /app

COPY package*.json ./
RUN npm install -g dotenv-cli cross-env
RUN npm install

COPY . .

ENV NODE_ENV=production

RUN npm run build:prod

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY /scripts/nginx-conf/stage/nginx.conf /etc/nginx/nfinx.conf

EXPOSE 80
#EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
