FROM node:16-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install --production=false

COPY . .

ENV NODE_ENV=stage
RUN npm run build:stage

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY /nginx/stage/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
