version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend-server
    environment:
      - NODE_ENV=production
    ports:
      - "3060:3060" # 프론트엔드 포트 설정 (React 등 프론트엔드 앱에 따라 변경)

  nginx:
    image: nginx:latest
    container_name: nginx-proxy-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d # 프론트엔드용 Nginx 설정 파일 마운트
      - ./nginx/certificates:/etc/letsencrypt
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certificates:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1d; done'"
    networks:
      - webnet

networks:
  webnet: