# 1. Node.js 기반 빌드 단계
FROM node:16-alpine AS build

WORKDIR /app

# 2. package.json 및 package-lock.json 복사
COPY package*.json ./

# 3. devDependencies 포함 모든 의존성 설치
RUN npm install --production=false

# 4. 소스 코드 복사
COPY . .

# 5. 빌드 실행
ENV NODE_ENV=production
RUN npm run build:prod

# 6. Nginx 기반 정적 파일 배포 단계
FROM nginx:alpine

# 7. 빌드 결과물 복사
COPY --from=build /app/build /usr/share/nginx/html

# 8. Nginx 설정 복사
COPY /nginx/conf.d/nginx.conf /etc/nginx/nginx.conf

# 9. 포트 노출
EXPOSE 80
EXPOSE 443

# 10. Nginx 실행
CMD ["nginx", "-g", "daemon off;"]